author: Logan Rosell


```{python}
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()
```


```{python}
data_dir = Path(os.environ["DATA_DIR"])
csv_path = data_dir / "county_fips_codes" / "county_2020_fips_codes.csv"
centroids_path = data_dir / "county_fips_codes" / "US_Counties_Centroids.csv"
```


```{python}
df_raw = pd.read_csv(
    csv_path, 
    encoding='latin-1', 
    delimiter="|", 
    dtype={'STATEFP': str, 'COUNTYFP': str, 'COUNTYNS': str}
)
```

```{python}
centroids_df = pd.read_csv(
    centroids_path,
    dtype={"FIPS_CD": str}
)
```

```{python}
centroids_df = centroids_df.rename(columns = {
    "FIPS_CD": "county_id",
    "LONGITUDE": "county_longitude",
    "LATITUDE": "county_latitude"
})

centroids_df["county_id"] = (centroids_df["county_id"]).str.zfill(5)

centroids_df["centroid_lon"] = pd.to_numeric(
    centroids_df["county_longitude"], errors="coerce"
)
centroids_df["centroid_lat"] = pd.to_numeric(
    centroids_df["county_latitude"], errors="coerce"
)
```
### FUNCSTAT Column data definition
A:  Identifies an active government providing primary general-purpose functions.
B:  Identifies an active government that is partially consolidated with another government but with separate officials providing primary general-purpose functions.
C:  Identifies an active government consolidated with another government with a single set of officials.
F:  Identifies a fictitious entity created to fill the Census Bureau's geographic hierarchy.
G:  Identifies an active government that is subordinate to another unit of government.
N:  Identifies a nonfunctioning legal entity.
S:  Identifies a statistical entity

```{python}
# Remove S rows since they statitical areas which overlap with counties
df_raw = df_raw[df_raw["FUNCSTAT"]!="S"]
```

### CLASSFP Column data definition
H1:  Identifies an active county or statistically equivalent entity that does not qualify under subclass C7 or H6.
H4:  Identifies a legally defined inactive or nonfunctioning county or statistically equivalent entity that does not qualify under subclass H6.
H5:  Identifies census areas in Alaska, a statistical county equivalent entity.
H6:  Identifies a county or statistically equivalent entity that is coextensive in area or governmentally consolidated with an incorporated place, part of an incorporated place, or a consolidated city.
C7:  Identifies an incorporated place that is an independent of any county.

```{python}
# Remove C7 observations, they are completely separate from counties
df_raw = df_raw[df_raw["CLASSFP"]!="C7"]
```

```{python}
# Remove US territories
df_raw = df_raw[~df_raw["STATE"].isin(['AS', 'GU', 'MP', 'PR', 'UM', 'VI'])]

```

```{python}
df_final = df_raw.rename(columns={
    "STATE": "state",
    "STATEFP": "state_fips_code",
    "COUNTYFP": "county_fips_code",
    "COUNTYNS": "county_ns_code",
    "COUNTYNAME": "county_name",
    "CLASSFP": "fips_class_code",
    "FUNCSTAT": "functional_status"
})
```

```{python}
df_final["county_id"] = df_final["state_fips_code"] + df_final["county_fips_code"]
```

```{python}
df_final = df_final.merge(
    centroids_df[["county_id", "centroid_lon", "centroid_lat"]],
    on="county_id",
    how="left"
)
```

```{python}
df_final.describe(include=[object])
```

```{python}
centroid_missing = df_final[df_final[["centroid_lon", "centroid_lat"]].isna().any(axis = 1)]
centroid_missing
# Looks like these are all non-mainland counties so we should be good
```

```{python}
database_url = os.getenv("DATABASE_URL")
engine = create_engine(database_url)
```


```{python}
df_final.to_sql(
    "us_counties",
    con=engine,
    if_exists="replace",
    index=False
)
```