author: Logan Rosell

```{python}
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()
```


```{python}
# make sure all column names are lowercase
def lower_cols(df):
    df.columns = df.columns.str.lower()
    return df
```

### Data Transformations
- create year column for each file then combine all files into one df
- concatonate fipstate and fipscty into unified county_id column
    - drop fipstate and fipscty columns
- rename columns to match ERD
- Drop all observations which are not at the industry sector aggregation level (naics 2 digit codes for example 11----)
- convert "N" to N/A
- convert 0 to N/A for rows and columns indicated by empflag
- Keep only years 2001 - 2022
- Make sure establishment columns are numeric data type

```{python}
# keep only rows with sector level codes
def remove_non_sector_rows(df):
    df = df[df["naics"].str.match(r'\d\d----')]
    # update index numbers since last operation leaves lots of gaps in index by removing rows
    df = df.reset_index(drop=True)
    return df
```

```{python}
# keep only rows with niacs code '518///' for data center employment specifically
def remove_non_dc_employment_rows(df):
    df = df[df["naics"]=='518///']
    # update index numbers since last operation leaves lots of gaps in index by removing rows
    df = df.reset_index(drop=True)
    return df
```

```{python}
# drop all columns not industry code or county id related
def drop_non_industry_or_county_id_cols(df):
    df = df[["naics", "fipscty", "fipstate", "emp", "ap"]]
    # update index numbers since last operation leaves lots of gaps in index by removing rows
    df = df.reset_index(drop=True)
    return df
```

```{python}
#rename columns to match ERD
def update_col_names(df):
    df = df.rename(columns={
        "naics": "naics_industry_code",
        "emp": "tot_employee_count",
        "ap": "annual_payroll",
        "est": "tot_establishment_count",
        "n1_4": "est<5",
        "n<5": "est<5",
        "n5_9": "est5_9",
        "n10_19": "est10_19",
        "n20_49": "est20_49",
        "n50_99": "est50_99",
        "n100_249": "est100_249",
        "n250_499": "est250_499", 
        "n500_999": "est500_999",
        "n1000": "est>1000",
        "n1000_1": "est1000_1500",
        "n1000_2": "est1500_2500",
        "n1000_3": "est2500_5000",
        "n1000_4": "est>5000"
    })
    return df
```

flag values key
A       0-19
B       20-99
C       100-249
E       250-499
F       500-999
G       1,000-2,499
H       2,500-4,999
I       5,000-9,999
J       10,000-24,999
K       25,000-49,999
L       50,000-99,999
M       100,000 or More

```{python}
# return emp columns which correspond to the given emp flag
def emp_cols (flag_value):
    if flag_value == "A":
        return ['est<5', 'est5_9', 'est10_19']
    if flag_value == "B":
        return ['est20_49', 'est50_99']
    if flag_value == "C":
        return ['est100_249']
    if flag_value == "E":
        return ["est250_499"]
    if flag_value == "F":
        return ['est500_999']
    if flag_value == "G":
        return ['est1000_1500', 'est1500_2500']
    if flag_value == "H":
        return ['est2500_5000']
    if flag_value == "I":
        return ['est>5000']
    else:
        return "not in range"
```

```{python}
# convert 0 to N/A for rows and columns indicated by empflag

def make_zero_na_according_to_emp_flag(df):
    if 'empflag' in df.columns:
        for i in range(0,len(df["empflag"])):
            flag_value = df.loc[:,"empflag"].iloc[i]
            if flag_value in ["A", "B", "C", "E", "F", "G", "H", "I"]:
                cols = emp_cols(flag_value)
                row_label = df.index[i]
                df.loc[row_label, cols] = pd.NA
    return df

def make_zero_na_according_to_emp_flag_fast(df):
    if 'empflag' in df.columns:
        target_flags = ["A", "B", "C", "E", "F", "G", "H", "I"]
        valid_mask = df['empflag'].isin(target_flags)
        for flag_value, sub_df in df[valid_mask].groupby('empflag'):
            cols = emp_cols(flag_value)
            if isinstance(cols, str):
                cols = [cols]
            df.loc[sub_df.index, cols] = pd.NA
    return df
```

```{python}
# add year column
def add_year(df):
    df["year"] = int(f"20{file_number}")
    return df
```


```{python}
# combine state and county fips into county_id then drop them
def create_county_id_col(df):
    df["county_id"] = df["fipstate"] + df["fipscty"]
    df = df.drop(columns=["fipstate", "fipscty"])
    return df
```

```{python}
# drop uneeded columns

def drop_extra_cols(df):
    columns_to_drop = [
        "emp_nf", "qp1_nf", "ap_nf", 
        "empflag", "qp1", "censtate", "cencty"
    ]
    # drop any column present in the above list, if list contains column not found in df ignore the error and drop the ones that are found. 
    df = df.drop(columns=columns_to_drop, errors='ignore')
    return df
```


```{python}
# convert "N" in all est fields to N/A value
def convert_N_to_NA(df):
    est_col_names = ['est<5', 'est5_9', 'est10_19', 'est20_49',
        'est50_99', 'est100_249', 'est250_499', 'est500_999', 'est>1000',
        'est1000_1500', 'est1500_2500', 'est2500_5000', 'est>5000']
    df[est_col_names] = df[est_col_names].replace('N',pd.NA)
    return df
```

```{python}
def load_data(csv_path):
    df = pd.read_csv(
        csv_path,
        dtype = {
            "fipstate": str, 
            "FIPSTATE": str,
            "fipscty": str,
            "FIPSCTY": str}
    )
    return df
```

```{python}
# remove years outside of analysis window
def trim_years(df):
    df = df[df["year"] >= 2001]
    df = df[df["year"] <= 2022]
    return df
```

```{python}
# convert est columns from string to numeric data type
def est_cols_to_numeric(df):
    est_col_names = ['est<5', 'est5_9', 'est10_19', 'est20_49',
            'est50_99', 'est100_249', 'est250_499', 'est500_999', 'est>1000',
            'est1000_1500', 'est1500_2500', 'est2500_5000', 'est>5000']
    df[est_col_names] = df[est_col_names].apply(pd.to_numeric, errors='coerce')
    return df
```

```{python}
# convert VA independent cities to parent county and combine values
city_to_parent_county = {
    '51510': '51013',
    '51515': '51019',
    '51520': '51191',
    '51530': '51163',
    '51540': '51003',
    '51550': '51131',
    '51570': '51053',
    '51580': '51005',
    '51590': '51143',
    '51595': '51081',
    '51600': '51059',
    '51610': '51059',
    '51620': '51175',
    '51630': '51177',
    '51640': '51035',
    '51650': '51095',
    '51660': '51165',
    '51670': '51149',
    '51678': '51163',
    '51680': '51031',
    '51683': '51153',
    '51685': '51153',
    '51690': '51089',
    '51700': '51095',
    '51710': '51095',
    '51720': '51195',
    '51730': '51053',
    '51735': '51199',
    '51740': '51095',
    '51750': '51121',
    '51760': '51087',
    '51770': '51161',
    '51775': '51161',
    '51790': '51015',
    '51800': '51131',
    '51810': '51131',
    '51820': '51015',
    '51830': '51095',
    '51840': '51069'
}

def roll_up_va_cities_to_county(df):
    df["county_id"] = df["county_id"].replace(city_to_parent_county)
    df = df.groupby(["naics_industry_code", "county_id", "year"], as_index=False).sum()
    return df

```

### Main Execuation Loop

```{python}
data_dir = Path(os.environ["DATA_DIR"])
```



```{python}
# main loop
list_of_df = []

for y in np.arange(1,23):

    file_number = str(y).zfill(2)
    csv_path = data_dir / "business_patterns" / f"cbp{file_number}co.txt"

    df_raw = load_data(csv_path)
    df_raw = lower_cols(df_raw)
    df_raw = remove_non_sector_rows(df_raw)
    df_raw = update_col_names(df_raw)
    df_raw = drop_extra_cols(df_raw)
    df_raw = make_zero_na_according_to_emp_flag_fast(df_raw)
    df_raw = add_year(df_raw)
    df_raw = trim_years(df_raw)
    df_raw = create_county_id_col(df_raw)
    df_raw = convert_N_to_NA(df_raw)
    df_raw = est_cols_to_numeric(df_raw)
    df_raw = roll_up_va_cities_to_county(df_raw)

    list_of_df.append(df_raw)

df_final = pd.concat(list_of_df, ignore_index=True)
```

```{python}
# remove dashes from naics_industry_code column
df_final["naics_industry_code"] = df_final["naics_industry_code"].str.replace("-", "", regex=False)
```

```{python}
# remove all state-wide abbreviations
df_final = df_final[df_final["county_id"].str[2:5] != "999"]
```

```{python}
# setup connection variables to local sql db
database_url = os.getenv("DATABASE_URL")
engine = create_engine(database_url)
```

```{python}
# export cleaned data to sql table in local db
df_final.to_sql(
    "business_patterns",
    con=engine,
    if_exists="replace",
    index=False
)
```


### Create NAICS codes look up table 

Using 2022 codes (latest version as writing)
https://www.census.gov/naics/?58967?yearbck=2022

```{python}

naics_lookup = {
    "sector": [
        "11",
        "21",
        "22",
        "23",
        "31",
        "32",
        "33",
        "42",
        "44",
        "45",
        "48",
        "49",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "61",
        "62",
        "71",
        "72",
        "81",
        "92",
        "95",
        "99"
    ],
    "definition": [
        "Agriculture, Forestry, Fishing and Hunting",
        "Mining, Quarrying, and Oil and Gas Extraction",
        "Utilities",
        "Construction",
        "Manufacturing",
        "Manufacturing",
        "Manufacturing",
        "Wholesale Trade",
        "Retail Trade",
        "Retail Trade",
        "Transportation and Warehousing",
        "Transportation and Warehousing",
        "Information",
        "Finance and Insurance",
        "Real Estate and Rental and Leasing",
        "Professional, Scientific, and Technical Services",
        "Management of Companies and Enterprises",
        "Administrative and Support and Waste Management and Remediation Services",
        "Educational Services",
        "Health Care and Social Assistance",
        "Arts, Entertainment, and Recreation",
        "Accommodation and Food Services",
        "Other Services (except Public Administration)",
        "Public Administration",
        "Unknown",
        "Unknown"
    ],
}


naics_lookup = pd.DataFrame(naics_lookup)

naics_lookup.to_sql(
    "naics_code_look_up",
    con=engine,
    if_exists="replace",
    index=False
)

```

### Create Data Center Employment Table
NAICS code 518/// is Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services which is particularly relevant to our research question and thus worth saving as the only employment metric which is disaggregated from the sector level. 

```{python}
# main loop
list_of_df = []

for y in np.arange(1,23):

    file_number = str(y).zfill(2)
    csv_path = data_dir / "business_patterns" / f"cbp{file_number}co.txt"

    df_raw = load_data(csv_path)
    df_raw = lower_cols(df_raw)
    df_raw = remove_non_dc_employment_rows(df_raw)
    #df_raw = drop_non_industry_or_county_id_cols(df_raw)
    df_raw = update_col_names(df_raw)
    df_raw = drop_extra_cols(df_raw)
    #df_raw = make_zero_na_according_to_emp_flag_fast(df_raw)
    df_raw = add_year(df_raw)
    #df_raw = trim_years(df_raw)
    df_raw = create_county_id_col(df_raw)
    #df_raw = convert_N_to_NA(df_raw)
    #df_raw = est_cols_to_numeric(df_raw)
    df_raw = roll_up_va_cities_to_county(df_raw)

    list_of_df.append(df_raw)

df_final_dc_emp = pd.concat(list_of_df, ignore_index=True)
```


```{python}
# save data center employment data to SQL db
df_final_dc_emp.to_sql(
    "naics_518_data",
    con=engine,
    if_exists="replace",
    index=False
)
```