---
title: "Personal Income Cleaning"
format: html
---

# Personal Income Cleaning Script

## Import Raw Data

```{python}
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from utils import db_cleaning_utils as dbu

load_dotenv()
```

```{python}
data_dir = Path(os.environ["DATA_DIR"])
csv_path = data_dir / "personal_income" / "personal_income_data.csv"
```

```{python}
df_raw = pd.read_csv(csv_path, encoding='latin-1')
```

## Change Granularity

### Pivot to Long Format

```{python}
df_long = df_raw.melt(
    id_vars = ['GeoFIPS', 'GeoName', 'Region', 'TableName', 'LineCode', 'IndustryClassification','Description', 'Unit'],
    value_vars = [str(year) for year in range(1969, 2025)],
    var_name = 'year',
    value_name = 'personal_income_value'
    )
```

### Pivot on Description

```{python}
df_final = df_long.pivot(
    index = ["GeoFIPS", "GeoName", "year"],
    columns = "Description",
    values = "personal_income_value"
).reset_index()
```

## Clean Columns

### GeoFIPS

```{python}
# Get rid of the extra quotes
df_final["GeoFIPS"] = df_final["GeoFIPS"].str.replace('"','') 
```

### GeoName

```{python}
# Only keep counties (have a comma)
df_final = df_final[df_final["GeoName"].str.contains(',', na = False)].reset_index(drop=True)
```


### Only Keep Necessary Columns

```{python}
#df_final["state_code"] = df_final['state_code'].str.split(', ').str[-1]
```


Some of the state codes also have a trailing `*` that we'll want to remove

```{python}
#df_final["state_code"] = df_final['state_code'].str.split('*').str[0]
```

```{python}
# Drop GeoName and empty column
df_final = df_final.drop(columns = [
    "GeoName",
    np.nan,
    "Population (persons) 1/"
    #,"county",
    #"state_code"
    ])
```

### Update column names

```{python}
df_final = df_final.rename(columns={
    "Per capita personal income (dollars) 2/": "per_capita_personal_income_dollars",
    "Personal income (thousands of dollars) ": "personal_income_thousands_of_dollars",
    "GeoFIPS": "county_id"
})
```

### Update column types

```{python}
df_final["year"] = df_final["year"].astype(int)

value_columns = ["per_capita_personal_income_dollars", "personal_income_thousands_of_dollars"]

for col in value_columns:
    df_final[col] = pd.to_numeric(
        df_final[col], 
        errors='coerce'
    ).astype('Int64') 
```

```{python}
# remove leading space in county_id
df_final["county_id"] = df_final["county_id"].str.strip()
```

```{python}
# remove years outside of analysis window
def trim_years(df):
    df = df[df["year"] >= 2001]
    df = df[df["year"] <= 2022]
    return df

df_final = trim_years(df_final)
```

## Handel Virgina County Codes Mapping

The BEA creates synthetic FIPS codes for independent cities and the county they exist within. Documention on this within the apendix of their methodology here: https://www.bea.gov/sites/default/files/methodologies/lapi2016.pdf

We will be attributing the combined measurments for the independent city and its parent county just the standard county_id rather than the synthetic id. Not all our data sources use the synthetic id meaning that the county_id is more universal. 

```{python}

df_final = dbu.va_cities_to_parent_county(df_final)
# aggregate all values to be average for a given county in a given year
df_final = df_final.groupby(by=["year", "county_id"], as_index=False).sum()
```

```{python}
# keep only osbservations which are in the lower 48 states and DC
df_final = dbu.remove_rows_not_in_mainland_states(df_final, "county_id")
```

```{python}
# Remove non-valid Wisconsin county
df_final = df_final[df_final["county_id"] != "55901"]
```


## EDA

### Summary Statistics
```{python}
df_final.describe()
```

### Example Plots


```{python}
# income_means_year = df_final.groupby('year')[value_columns].mean()
```

#### Average Per Capita Income Over Time
```{python}
# sns.lineplot(income_means_year, x='year', y='per_capita_personal_income_dollars')

# plt.title("Average Per Capita Personal Income Over Time")
# plt.xlabel("Year")
# plt.ylabel("Per Capita Personal Income")

# plt.yticks(rotation=45)

# plt.show()
```

## Update child counties to use parent

```{python}
df_final = dbu.child_to_parent_county(
    df_final, 
    map_dict = {'46113': '46102', '12025': '12086', '24510': '24005', '29510': '29189', '32510': '32005', '46113': '46102'},
    cols_to_avg = ["per_capita_personal_income_dollars"]
    )
```

```{python}
# remove new fips county codes in CT
df_final = dbu.remove_new_ct_fips_codes(df_final)
```

# Export to database

```{python}
database_url = os.getenv("DATABASE_URL")
engine = create_engine(database_url)
```

```{python}
df_final.to_sql(
    "personal_income",
    con=engine,
    if_exists="replace",
    index=False
)
```