---
title: "GDP Cleaning"
format: html
---

# GDP Cleaning Script

## Import Raw Data

```{python}
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
import importlib
import utils.db_cleaning_utils as dbu
importlib.reload(dbu)

load_dotenv()
```

```{python}
data_dir = Path(os.environ["DATA_DIR"])
csv_path = data_dir / "gdp" / "gdp_data.csv"
```

```{python}
df_raw = pd.read_csv(csv_path, encoding='latin-1')
```

## Change Granularity

### Pivot to Long Format

```{python}
df_long = df_raw.melt(
    id_vars = ['GeoFIPS', 'GeoName', 'Region', 'TableName', 'LineCode', 'IndustryClassification','Description', 'Unit'],
    value_vars = [str(year) for year in range(2001, 2025)],
    var_name = 'year',
    value_name = 'gdp_value'
    )
```

### Pivot on Description

```{python}
df_final = df_long.pivot(
    index = ["GeoFIPS", "GeoName", "year"],
    columns = "Description",
    values = "gdp_value"
).reset_index()
```

## Clean Columns

### GeoFIPS

```{python}
# Get rid of the extra quotes
df_final["GeoFIPS"] = df_final["GeoFIPS"].str.replace('"','') 
```

### GeoName

```{python}
# Only keep counties (have a comma)
df_final = df_final[df_final["GeoName"].str.contains(',', na = False)].reset_index(drop=True)
```

### Only Keep Necessary Columns

```{python}
df_final = df_final[['GeoFIPS', 'Real GDP (thousands of chained 2017 dollars) ', 'Current-dollar GDP (thousands of current dollars) ', 'Chain-type quantity indexes for real GDP ', 'year']]
```

### Update column names

```{python}
# Then rename columns
df_final = df_final.rename(columns={
    "GeoFIPS": "county_id",
    "Chain-type quantity indexes for real GDP ": "quantity_index_gdp",
    "Current-dollar GDP (thousands of current dollars) ": "current_gdp_dollars_thousands",
    "Real GDP (thousands of chained 2017 dollars) ": "real_gdp_2017_dollars_thousands"
})
```

```{python}
# trim leading spaces in county_id
df_final["county_id"] = df_final["county_id"].str.strip()
```

### Update column types

```{python}
df_final["year"] = df_final["year"].astype(int)

df_final["quantity_index_gdp"] = pd.to_numeric(
    df_final["quantity_index_gdp"], 
    errors='coerce'
)

df_final["current_gdp_dollars_thousands"] = pd.to_numeric(
    df_final["current_gdp_dollars_thousands"], 
    errors='coerce'
).astype('Int64') 

df_final["real_gdp_2017_dollars_thousands"] = pd.to_numeric(
    df_final["real_gdp_2017_dollars_thousands"], 
    errors='coerce'
).astype('Int64')
```

```{python}
# remove years outside of analysis window
def trim_years(df):
    df = df[df["year"] >= 2001]
    df = df[df["year"] <= 2022]
    return df

df_final = trim_years(df_final)
```

## Handel Virgina County Codes Mapping

The BEA creates synthetic FIPS codes for independent cities and the county they exist within. Documention on this within the apendix of their methodology here: https://www.bea.gov/sites/default/files/methodologies/lapi2016.pdf

We will be attributing the combined measurments for the independent city and its parent county just the standard county_id rather than the synthetic id. Not all our data sources use the synthetic id meaning that the county_id is more universal. 

```{python}
df_final = dbu.va_cities_to_parent_county(df_final)
```

```{python}
# remove independent cities now that they are attributed to parent county
va_indy_cities = ['51510', '51515', '51520', '51530', '51540', '51550', '51570', '51580', '51590', '51595', '51600', '51610', '51620', '51630', '51640', '51650', '51660', '51670', '51678', '51680', '51683', '51685', '51690', '51700', '51710', '51720', '51730', '51735', '51740', '51750', '51760', '51770', '51775', '51790', '51800', '51810', '51820', '51830', '51840']

df_final = df_final[~df_final['county_id'].isin(va_indy_cities)]
```

```{python}
# keep only osbservations which are in the lower 48 states and DC
df_final = dbu.remove_rows_not_in_mainland_states(df_final, "county_id")
```

## EDA

### Summary Statistics
```{python}
df_final.describe()
```

### Example Plots

```{python}
# gdp_cols = ['quantity_index_gdp', 'current_gdp_dollars_thousands', 'real_gdp_2017_dollars_thousands']
```

```{python}
# gdp_means_year = df_final.groupby('year')[gdp_cols].mean()
```

#### Average County GDP Over Time (for Current-Dollar & Real GDP)
```{python}
# sns.lineplot(gdp_means_year, x='year', y='current_gdp_dollars_thousands', label='Current-Dollar GDP')

# sns.lineplot(gdp_means_year, x='year', y='real_gdp_2017_dollars_thousands', label='Real GDP')

# plt.legend()

# plt.title("Average County GDP Over Time")
# plt.xlabel("Year")
# plt.ylabel("GDP (thousands of dollars)")

# ax = plt.gca()
# ax.ticklabel_format(style='plain')

# plt.yticks(rotation=45)

# plt.show()
```

#### Average County GDP Over Time (for Quantity Index)
```{python}
# sns.lineplot(gdp_means_year, x='year', y='quantity_index_gdp')

# plt.title("Average County Quantity Index for GDP Over Time")
# plt.xlabel("Year")
# plt.ylabel("Quantity Index for Real GDP")

# plt.yticks(rotation=45)

# plt.show()
```

## Update child counties to use parent

```{python}
df_final = dbu.child_to_parent_county(
    df_final, 
    map_dict = {'46113': '46102', '12025': '12086', '24510': '24005', '29510': '29189', '32510': '32005', '46113': '46102'},
    cols_to_avg = ["quantity_index_gdp"]
    )
```

```{python}
# remove new fips county codes in CT
df_final = dbu.remove_new_ct_fips_codes(df_final)
```

# Export to database

```{python}
database_url = os.getenv("DATABASE_URL")
engine = create_engine(database_url)
```

```{python}
df_final.to_sql(
    "gdp",
    con=engine,
    if_exists="replace",
    index=False
)
```