---
title: "Linear Regression"
format: html
---

```{python}
import pandas as pd
from pandas.api.types import is_numeric_dtype
import numpy as np
from pathlib import Path
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import importlib
import utils.db_cleaning_utils as dbu
import utils.ml_modeling_utils as mlu
importlib.reload(dbu)
importlib.reload(mlu)

load_dotenv()
data_dir = Path(os.environ["DATA_DIR"])
```

```{python}
# setup connection variables to local sql db
database_url = os.getenv("DATABASE_URL")
engine = create_engine(database_url)
```

```{python}
# Load data
dc_df = pd.read_sql_table("naics_518_establishments", engine, schema="transformed")
air_df = pd.read_sql_table("air_quality", engine, schema="transformed")
bus_df = pd.read_sql_table("business_patterns", engine, schema="transformed")
code_df = pd.read_sql_table("naics_code_look_up", engine)
gdp_df = pd.read_sql_table("gdp", engine, schema="transformed")
inc_df = pd.read_sql_table("personal_income", engine, schema="transformed")
pop_df = pd.read_sql_table("population", engine)
perm_df = pd.read_sql_table("res_construction_permits", engine, schema="transformed")
emp_df = pd.read_sql_table("unemployment", engine, schema="transformed")
county_df = pd.read_sql_table("us_counties", engine)
```

## Create Table for Regressions

### Helper Functions

```{python}
def county_average(df, include_cols = None):
    if "county_id" not in df.columns:
        raise ValueError("No `county_id` column found.")

    if include_cols is None:
        include_cols = [
            col for col in df.columns
            if col != "county_id" and is_numeric_dtype(df[col])
        ]
    else:
        non_num_cols = [
            col for col in include_cols 
            if col =="county_id" or not is_numeric_dtype(df[col])
            ]
        if non_num_cols:
            raise ValueError(f"Only numeric columns are allowed in `include_cols`. Non-numeric columns: {non_num_cols}")

    # Since there are no years for datacenters, take average of all years for each county
    out_df = (df[["county_id"] + include_cols].groupby("county_id", as_index = False).mean())

    return out_df
```

```{python}
def combine_dfs(base_df, dfs_to_join):
    out_df = base_df.copy()

    for i, df in enumerate(dfs_to_join):
        if "county_id" not in df.columns:
            raise ValueError(f"No `county_id` column found in dfs_to_join[{i}]")

        # Make sure all tables only have one row per county
        dupes = df["county_id"][df[["county_id","year"]].duplicated()].unique()
        if len(dupes) > 0:
            raise ValueError(f"dfs_to_join[{i}] is not unique on `county_id and year`. Problematic Counties: {list(dupes)}")

        out_df = pd.merge(out_df, df, how = "left", on = ["county_id", "year"], validate = "one_to_one")

    missing_summary_table = (
        out_df.isna()
        .mean()
        .sort_values(ascending = False)
        .rename("missing_share")
        .reset_index()
        .rename(columns={"index":"column"})
    )

    print("Missing Summary: \n", missing_summary_table)

    return out_df
```

### Create final table

```{python}
bus_county_year_df = dbu.all_county_years(county_df, year_start=2001, year_end=2022)

pivoted_bus_df = mlu.pivot_naics(bus_df, code_df)

final_bus_df = bus_county_year_df.merge(pivoted_bus_df, on=["county_id", "year"], how="left")

final_bus_df = (
    final_bus_df
    .groupby("county_id", group_keys=False)
    .apply(dbu.impute_all_columns_for_county)
)

final_bus_df = dbu.spatial_then_yoy(final_bus_df, county_df)
```

```{python}
# Create county_year dataframe for merging below
county_year_df = dbu.all_county_years(county_df, year_start=2007, year_end=2022)
```

```{python}
final_df = combine_dfs(county_year_df, [air_df, final_bus_df, gdp_df, inc_df, pop_df, perm_df, emp_df, dc_df])
```

### Clean up final table

```{python}
# Make applicable columns per-capita
bus_cols = ["tot_employee_count", "annual_payroll", "tot_establishment_count"]

cols = [c for c in final_df.columns if any(l in c for l in bus_cols)]

per_capita_cols = [
    "real_gdp_2017_dollars_thousands",
    "real_gdp_2017_dollars_thousands_spatial_weighted_avg_5",
    "personal_income_thousands_of_dollars",
    "personal_income_thousands_of_dollars_spatial_weighted_avg_5",
    "all_permits",
    "all_permits_spatial_weighted_avg_5",
    "single_family_permits",
    "single_family_permits_spatial_weighted_avg_5",
    "all_multifamily_permits",
    "all_multifamily_permits_spatial_weighted_avg_5"
] + cols

final_df = mlu.make_per_capita(final_df, per_capita_cols)
```

```{python}
# Per-capita data centers (don't drop original though)
final_df["datacenters_per_capita"] = final_df["estabs"] / final_df["population"]
final_df["datacenters_spatial_per_capita"] = final_df["estabs_spatial_weighted_avg_5"] / final_df["population"]
```

```{python}
# Rename for clarity
final_df = final_df.rename(columns = {
    "annual_payroll_per_capita": "annual_payroll_thousands_per_capita", 
    "estabs": "datacenters",
    "estabs_spatial_weighted_avg_5": "datacenters_spatial_weighted_avg_5",
    "unemployment_rate": "unemployment_rate_pct"
    })

# Drop temporal columns as the regression model should be able to handle this without needing extra columns
final_df = final_df.drop(columns = final_df.columns[final_df.columns.str.contains("yoy", case=False)])

final_df = final_df.sort_values(["county_id", "year"]).reset_index(drop=True)
```

## Feature Engineering

### EDA

#### Find Columns that are still skewed
```{python}
mlu.eda_summary(final_df)
```

### Select Columns for final regressions

```{python}
regression_cols = [
    "county_id",
    "year",

    # treatment
    "datacenters",
    "datacenters_spatial_weighted_avg_5",
    "datacenters_per_capita",
    "datacenters_spatial_per_capita",

    # core controls
    "population",
    "real_gdp_2017_dollars_thousands_per_capita",
    "personal_income_thousands_of_dollars_per_capita",
    "unemployment_rate_pct",
    "single_family_permits_per_capita",
    "all_multifamily_permits_per_capita",

    # environmental
    "pm25_mean_daily_avg",
    "pm25_mean_daily_avg_spatial_weighted_avg_5",

    # business sectors
    "tot_employee_count_industrial_per_capita",
    "tot_employee_count_information_per_capita",
    "tot_employee_count_professional_per_capita",
    "tot_employee_count_public_services_per_capita",
    "tot_employee_count_primary_industries_per_capita",
    "tot_employee_count_trade_transport_per_capita"
]

regression_df = final_df[regression_cols].copy()
```

```{python}
summary_df = mlu.eda_summary(regression_df, acceptable_skew = 2.0)
summary_df
```

```{python}
regression_df = mlu.apply_suggested_transforms(regression_df, summary_df, cols_to_exclude = ["datacenters", "datacenters_spatial_weighted_avg_5"])
regression_df
```

```{python}
regression_df = mlu.add_lags(regression_df, "datacenters", lags=(1, 2, 3))
regression_df = mlu.add_lags(regression_df, "datacenters_spatial_weighted_avg_5", lags=(1, 2, 3))
```

```{python}
# Add years for trend models
regression_df["year_num"] = regression_df["year"] - regression_df["year"].min()
```

```{python}
datacenter_cols = [col for col in regression_df.columns if 'datacenter' in col]

exclude_from_lasso = ["year_num"] + [
    c for c in datacenter_cols
    if c not in {"datacenters_lag2", "datacenters_spatial_weighted_avg_5_lag2"}
]
```

## Linear Regressions

### Unemployment

```{python}
mlu.run_lasso(regression_df, "unemployment_rate_pct")
```

```{python}
unemp_cols = ["pm25_mean_daily_avg_spatial_weighted_avg_5",
    "personal_income_thousands_of_dollars_per_capita_log",
    "tot_employee_count_industrial_per_capita_log1p",
    "single_family_permits_per_capita_log1p",
    "population_log",
    "tot_employee_count_professional_per_capita_log1p",
    "real_gdp_2017_dollars_thousands_per_capita_log"
    ]
```

```{python}
mlu.show_correlation_heat_map(regression_df[unemp_cols])
```

```{python}
mlu.column_selector(
    regression_df[unemp_cols],
    outlier_sd_cut_off = 3.0,
    only_normal = True,
    return_report = True
    )
```

```{python}
# Baseline
x_base = unemp_cols + ["datacenters", "datacenters_spatial_weighted_avg_5"]
model_base = mlu.run_linear_regression(regression_df, "unemployment_rate_pct", x_base)

x_lag1 = unemp_cols + ["datacenters_lag1", "datacenters_spatial_weighted_avg_5_lag1"]
model_lag1 = mlu.run_linear_regression(regression_df, "unemployment_rate_pct", x_lag1)

x_lag2 = unemp_cols + ["datacenters_lag2", "datacenters_spatial_weighted_avg_5_lag2"]
model_lag2 = mlu.run_linear_regression(regression_df, "unemployment_rate_pct", x_lag2)

x_lag3 = unemp_cols + ["datacenters_lag3", "datacenters_spatial_weighted_avg_5_lag3"]
model_lag3 = mlu.run_linear_regression(regression_df, "unemployment_rate_pct", x_lag3)
```

```{python}
mlu.compare_models(
    [model_base, model_lag1, model_lag2, model_lag3],
    ["base", "lag1", "lag2", "lag3"]
)
```


```{python}
x_lag2_trend = unemp_cols + ["year_num", "datacenters_lag2", "datacenters_spatial_weighted_avg_5_lag2"]

model_lag2_trend = mlu.run_linear_regression(regression_df, "unemployment_rate_pct", x_lag2_trend, year_fe = False)
```

```{python}
mlu.compare_models(
    [model_lag2, model_lag2_trend],
    ["fixed effect year", "yearly trend"]
)
```

#### Analysis

For this regression I tested a few different types of models, including different lags and a fixed effect vs. yearly trend. Ultimately, a two-year fixed effect had the best results. For consistency in analysis, I used this two-year fixed effect for all other models.

Findings:

* R2 = 0.847
* 2 year lagged data centers had p-value of 0.004 and coefficient of 0.0033
    * This can be interpreted as one new datacenter being correlated with a 0.0033% increase in unemployment
* 2 year lagged *spatial* data centers had a p-value of 0.186
    * This can be interpreted as inverse-distance weighted average of the 5 nearest counties’ data centers having no significant correlation with unemployment
* There is a bit of a wedge shape towards 0 with the residuals graph, but otherwise residuals look fairly evenly distributed
* The Q-Q plot has some variance on the left tail, and fairly high variance on the right tail.
* All VIFs are well below 5


### Personal Income

```{python}
mlu.run_lasso(regression_df, "personal_income_thousands_of_dollars_per_capita_log", exclude_cols = exclude_from_lasso)
```

```{python}
inc_cols = [
    "real_gdp_2017_dollars_thousands_per_capita_log",
    "unemployment_rate_pct",
    "tot_employee_count_professional_per_capita_log1p",
    "single_family_permits_per_capita_log1p",
    "pm25_mean_daily_avg",
    "tot_employee_count_public_services_per_capita",
    "population_log",
    "tot_employee_count_trade_transport_per_capita_log1p",
    "tot_employee_count_primary_industries_per_capita_log1p"
    ]
```

```{python}
x_lag2 = inc_cols + ["datacenters_lag2", "datacenters_spatial_weighted_avg_5_lag2"]
model_lag2 = mlu.run_linear_regression(regression_df, "personal_income_thousands_of_dollars_per_capita_log", x_lag2)
```

#### Analysis

Findings:

* R2 = 0.965
* 2 year lagged data centers had p-value of 0.000 and coefficient of 0.0004 
    * This can be interpreted as one new datacenter being correlated with a 0.04% increase in personal income
* 2 year lagged *spatial* data centers had a p-value of 0.000 and a coefficient of 0.0007
    * This can be interpreted as inverse-distance weighted average of the 5 nearest counties’ data centers being correlated with a 0.07% increase in personal income
* Overall the residuals look fairly evenly distributed other than 2 clumps near 0 and 2
* The Q-Q plot has fairly high variance on both ends
* All VIFs are well below 5

### Single Family Permits

```{python}
mlu.run_lasso(regression_df, "single_family_permits_per_capita_log1p", exclude_cols = exclude_from_lasso)
```

```{python}
con_cols = [
    "real_gdp_2017_dollars_thousands_per_capita_log",
    "unemployment_rate_pct",
    "tot_employee_count_professional_per_capita_log1p",
    "pm25_mean_daily_avg",
    "tot_employee_count_public_services_per_capita",
    "population_log",
    "tot_employee_count_trade_transport_per_capita_log1p",
    "tot_employee_count_primary_industries_per_capita_log1p",
    "personal_income_thousands_of_dollars_per_capita_log",
    "tot_employee_count_industrial_per_capita_log1p",
    ]
```

```{python}
x_lag2 = con_cols + ["datacenters_lag2", "datacenters_spatial_weighted_avg_5_lag2"]
model_lag2 = mlu.run_linear_regression(regression_df, "single_family_permits_per_capita_log1p", x_lag2)
```

#### Analysis

Findings:

* R2 = 0.773
* 2 year lagged data centers had p-value of 0.000 and coefficient of 0.000008774
    * This can be interpreted as one new datacenter being correlated with a 0.00088% increase in single family permits
* 2 year lagged *spatial* data centers had a p-value of 0.883
    * This can be interpreted as inverse-distance weighted average of the 5 nearest counties’ data centers having no significant correlation with single family permits
* There is a bit of a wedge shape towards 0 with the residuals graph, but otherwise residuals look fairly evenly distributed
* The Q-Q plot has fairly high variance on both ends
* All VIFs are well below 5

### Multifamily Permits

```{python}
mlu.run_lasso(regression_df, "all_multifamily_permits_per_capita_log1p", exclude_cols = exclude_from_lasso)
```

```{python}
multi_con_cols = [
    "real_gdp_2017_dollars_thousands_per_capita_log",
    "unemployment_rate_pct",
    "tot_employee_count_professional_per_capita_log1p",
    "tot_employee_count_public_services_per_capita",
    "population_log",
    "tot_employee_count_trade_transport_per_capita_log1p",
    "tot_employee_count_industrial_per_capita_log1p",
    ]
```

```{python}
x_lag2 = multi_con_cols + ["datacenters_lag2", "datacenters_spatial_weighted_avg_5_lag2"]
model_lag2 = mlu.run_linear_regression(regression_df, "all_multifamily_permits_per_capita_log1p", x_lag2)
```

#### Analysis

Findings:

* R2 = 0.347
* 2 year lagged data centers had p-value of 0.000 and coefficient of 0.000009727
    * This can be interpreted as one new datacenter being correlated with a 0.00097% increase in multifamily permits
* 2 year lagged *spatial* data centers had a p-value of 0.286
    * This can be interpreted as inverse-distance weighted average of the 5 nearest counties’ data centers having no significant correlation with multifamily permits
* The residuals graph is highly irregular and has clear patterns
* The Q-Q plot has very high variance on both ends
* All VIFs are well below 5

### GDP

```{python}
mlu.run_lasso(regression_df, "real_gdp_2017_dollars_thousands_per_capita_log", exclude_cols = exclude_from_lasso)
```

```{python}
gdp_cols = [
    "tot_employee_count_professional_per_capita_log1p",
    "pm25_mean_daily_avg_spatial_weighted_avg_5",
    "tot_employee_count_public_services_per_capita",
    "population_log",
    "tot_employee_count_trade_transport_per_capita_log1p",
    "tot_employee_count_primary_industries_per_capita_log1p",
    "tot_employee_count_industrial_per_capita_log1p",
    "single_family_permits_per_capita_log1p"
    ]
```

```{python}
x_lag2 = gdp_cols + ["datacenters_lag2", "datacenters_spatial_weighted_avg_5_lag2"]
model_lag2 = mlu.run_linear_regression(regression_df, "real_gdp_2017_dollars_thousands_per_capita_log", x_lag2)
```

#### Analysis

Findings:

* R2 = 0.935
* 2 year lagged data centers had p-value of 0.000 and coefficient of 0.0010
    * This can be interpreted as one new datacenter being correlated with a 0.10% increase in gdp
* 2 year lagged *spatial* data centers had a p-value of 0.000 and a coefficient of 0.0009
    * This can be interpreted as inverse-distance weighted average of the 5 nearest counties’ data centers being correlated with a 0.09% increase in gdp
* The residuals graph is mostly regularly distributed with some outliers on the right side
* The Q-Q plot has somewhat high variance on both ends
* All VIFs are well below 5

### Air Quality

```{python}
exclude_air = exclude_from_lasso + ["pm25_mean_daily_avg_spatial_weighted_avg_5"]

mlu.run_lasso(regression_df, "pm25_mean_daily_avg", exclude_cols = exclude_air)
```

```{python}
air_cols = [
    "tot_employee_count_professional_per_capita_log1p",
    "unemployment_rate_pct",
    "tot_employee_count_public_services_per_capita",
    "population_log",
    "tot_employee_count_primary_industries_per_capita_log1p",
    "tot_employee_count_industrial_per_capita_log1p",
    "single_family_permits_per_capita_log1p",
    "personal_income_thousands_of_dollars_per_capita_log",
    "real_gdp_2017_dollars_thousands_per_capita_log"
    ]
```

```{python}
x_lag2 = air_cols + ["datacenters_lag2", "datacenters_spatial_weighted_avg_5_lag2"]
model_lag2 = mlu.run_linear_regression(regression_df, "pm25_mean_daily_avg", x_lag2)
```

#### Analysis

Findings:

* R2 = 0.819
* 2 year lagged data centers had p-value of 0.901
    * This can be interpreted as one new datacenter not being correlated with an change in air quality
* 2 year lagged *spatial* data centers had a p-value of 0.000 and a coefficient of 0.0071
    * This can be interpreted as inverse-distance weighted average of the 5 nearest counties’ data centers being correlated with a 0.0071 point increase in mean daily avg pm25. 
* The residuals graph is very regularly distributed
* The Q-Q plot has somewhat some small variance on the left side and high variance on the right side
* All VIFs are well below 5

### Spatial Air Quality

```{python}
exclude_air = exclude_from_lasso + ["pm25_mean_daily_avg"]

mlu.run_lasso(regression_df, "pm25_mean_daily_avg_spatial_weighted_avg_5", exclude_cols = exclude_air)
```

```{python}
spatial_air_cols = [
    "tot_employee_count_professional_per_capita_log1p",
    "unemployment_rate_pct",
    "tot_employee_count_public_services_per_capita",
    "population_log",
    "tot_employee_count_primary_industries_per_capita_log1p",
    "tot_employee_count_industrial_per_capita_log1p",
    "single_family_permits_per_capita_log1p",
    "personal_income_thousands_of_dollars_per_capita_log",
    "real_gdp_2017_dollars_thousands_per_capita_log"
    ]
```

```{python}
x_lag2 = spatial_air_cols + ["datacenters_lag2", "datacenters_spatial_weighted_avg_5_lag2"]
model_lag2 = mlu.run_linear_regression(regression_df, "pm25_mean_daily_avg_spatial_weighted_avg_5", x_lag2)
```

#### Analysis

Findings:

* R2 = 0.817
* 2 year lagged data centers had p-value of 0.846
    * This can be interpreted as one new datacenter not being correlated with an change in the inverse-distance weighted average of air quality
* 2 year lagged *spatial* data centers had a p-value of 0.000 and a coefficient of 0.0069
    * This can be interpreted as inverse-distance weighted average of the 5 nearest counties’ data centers being correlated with a 0.0069 point increase in the inverse-distance weighted average of mean daily avg pm25. 
* The residuals graph is very regularly distributed
* The Q-Q plot has somewhat some small variance on the left side and high variance on the right side
* All VIFs are well below 5

