---
title: Predict The Presence of Data Center(s) in a County
author: Logan Rosell
---

## Goal
To get a sense of how predictive each of our available x variables are of whether a county does or does not have data centers we will create a simple Logistic Regression model including all variables. 



## Logistic Regression Model

```{python}
import pandas as pd
from pandas.api.types import is_numeric_dtype
import numpy as np
from pathlib import Path
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
import subprocess
import sys
from skimpy import skim
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
from sklearn.metrics import PredictionErrorDisplay
from scipy.stats import probplot
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.preprocessing import OneHotEncoder
from scipy import stats
from statsmodels.stats.multitest import multipletests
from statsmodels.stats.stattools import durbin_watson
from imblearn.over_sampling import SMOTE
from imblearn.ensemble import BalancedRandomForestClassifier

load_dotenv()
data_dir = Path(os.environ["DATA_DIR"])
```

```{python}
# setup connection variables to local sql db
database_url = os.getenv("DATABASE_URL")
engine = create_engine(database_url)
```

```{python}
# Load data

# this function cleans up the weird column name formatting SQLAlchemy addes to the df when loading. 
def load_table(table_name, engine):
    df = pd.read_sql_table(table_name, engine)
    df.columns = [str(col) for col in df.columns]
    return df


dc_df = load_table("naics_518_establishments", engine)
air_df = load_table("air_quality", engine)
bus_df = load_table("business_patterns", engine)
gdp_df = load_table("gdp", engine)
inc_df = load_table("personal_income", engine)
pop_df = load_table("population", engine)
perm_df = load_table("res_construction_permits", engine)
emp_df = load_table("unemployment", engine)
county_df = load_table("us_counties", engine)
```

## Create Table for models

### Helper Functions

```{python}
def combine_dfs(base_df, dfs_to_join):
    out_df = base_df.copy()

    for i, df in enumerate(dfs_to_join):
        if "county_id" not in df.columns:
            raise ValueError(f"No `county_id` column found in dfs_to_join[{i}]")

        # Make sure all tables only have one row per county
        dupes = df["county_id"][df["county_id"].duplicated()].unique()
        if len(dupes) > 0:
            raise ValueError(f"dfs_to_join[{i}] is not unique on `county_id`. Problematic Counties: {list(dupes)}")

        out_df = pd.merge(out_df, df, how = "left", on = "county_id", validate = "one_to_one")

    missing_summary_table = (
        out_df.isna()
        .mean()
        .sort_values(ascending = False)
        .rename("missing_share")
        .reset_index()
        .rename(columns={"index":"column"})
    )

    print("Missing Summary: \n", missing_summary_table)

    return out_df
```

```{python}
# slice df to specific year
def return_specific_year(df, year):
    assert"year" in df.columns, "data frame does not have a year column"
    year = int(year)
    sliced_df = df[df["year"]==year]
    sliced_df = sliced_df.drop(columns = ["year"])
    return sliced_df
```

```{python}
# keep only 2022 (closest to when we know data center counts to be true)

df_with_years = [dc_df, air_df, bus_df, gdp_df, inc_df, pop_df, perm_df, emp_df]

dfs_only_2022 = [return_specific_year(x, 2022) for x in df_with_years]

```


```{python}
# Aggregate all industry codes per county into one summed row

dfs_only_2022[2] = dfs_only_2022[2].groupby(
    ["county_id"],
    as_index=False
    ).sum()

dfs_only_2022[2] = dfs_only_2022[2].drop(columns = ["naics_industry_code"])
```

```{python}
# Add column to county_df which indicates the presence of one or more data centers in a county
dc_df_2022 = dfs_only_2022[0]

counties_with_dc = dc_df_2022["county_id"].unique()

county_df["has_datacenter"] = county_df["county_id"].isin(counties_with_dc).astype(int)
county_df = county_df[[
    "county_id",
    "has_datacenter",
    "centroid_lon",
    "centroid_lat",
    "land_area_sqmi",
    "water_area_sqmi"
    ]]
```

```{python}
# one-hot-encode state to act as a regional indicator variable 

# encoder = OneHotEncoder(sparse_output=False)
# encoded_states = encoder.fit_transform(county_df[["state"]])
# encoded_df = pd.DataFrame(
#     encoded_states,
#     columns=encoder.get_feature_names_out(["state"])
# )

# county_df = pd.concat(
#     [county_df.drop(columns=["state"]), encoded_df],
#     axis=1
# )
```

```{python}
# combine all data together
mega_df = combine_dfs(county_df, dfs_only_2022[1:])
```

```{python}
# Make applicable columns per-capita
def make_per_capita(df, per_capita_cols):

    for col in per_capita_cols:
        df[f"{col}_per_capita"] = df[col] / df["population"]

    df = df.drop(columns=per_capita_cols)
    return df


per_capita_cols = [
       'tot_employee_count', 'annual_payroll', 'tot_establishment_count',
       'est<5', 'est5_9', 'est10_19', 'est20_49', 'est50_99', 'est100_249',
       'est250_499', 'est500_999', 'est>1000', 'est1000_1500', 'est1500_2500',
       'est2500_5000', 'est>5000', 'real_gdp_2017_dollars_thousands',
       'current_gdp_dollars_thousands',
       'all_permits',
       'single_family_permits', 'all_multifamily_permits',
       'multifamily_permits_2_units', 'multifamily_permits_3_4_units',
       'multifamily_permits_5_or_more_units'
]

mega_df = make_per_capita(mega_df, per_capita_cols)
```

```{python}
# remove all rows with NA values in preparating of statitical tests which fail on NA values. 
mega_df = mega_df.dropna()
```

## EDA
 
 ```{python}
# compare the mean value for all features between counties with and without datacenters
dc_counties =  mega_df[mega_df["has_datacenter"]==1]
dc_counties = dc_counties.drop(columns = ["county_id", "has_datacenter"])
dc_county_means = dc_counties.mean().to_frame()
dc_county_means["has_dc"] = "no"
dc_county_means.columns = ["mean", "has_dc"]

non_dc_counties =  mega_df[mega_df["has_datacenter"]==0]
non_dc_counties = non_dc_counties.drop(columns = ["county_id", "has_datacenter"])
non_dc_county_means = non_dc_counties.mean().to_frame()
non_dc_county_means["has_dc"] = "yes"
non_dc_county_means.columns = ["mean", "has_dc"]

comparing_means_df = pd.concat([dc_county_means, non_dc_county_means], axis=0)
comparing_means_df = comparing_means_df.reset_index().rename(columns={"index": "feature"})

feature_list = comparing_means_df["feature"].unique()

for i in feature_list:
    sns.barplot(
        x = "feature",
        y = "mean",
        hue = "has_dc",
        data = comparing_means_df[comparing_means_df["feature"]==i]
    )
    plt.show()

 ```


Check for statistically significantly different means between counties with and without data centers using the Mann-Whitney U Test. Because checking 40 different features at the same time increases the risk of finding a fase-positive we are using the Benjamini-Hochberg correction. 
```{python}
# Check for statistically significantly different means between counties with and without data centers using the Mann-Whitney U Test

dc_group = mega_df[mega_df["has_datacenter"] == 1]
non_dc_group = mega_df[mega_df["has_datacenter"] == 0]

# all numeric columns
features = list(mega_df.columns)[2:]

results = []

for col in features:
    g1 = dc_group[col].dropna()
    g2 = non_dc_group[col].dropna()
    
    median_dc = g1.median()
    median_non_dc = g2.median()
    
    stat, p_val = stats.mannwhitneyu(g1, g2, alternative="two-sided")
    
    results.append({
        "feature": col,
        "median_with_dc": median_dc,
        "median_no_dc": median_non_dc,
        "p_value": p_val
    })

results_df = pd.DataFrame(results)

# Benjamini-Hochberg FDR correction
reject, p_corrected, _, _ = multipletests(results_df["p_value"], alpha=0.05, method="fdr_bh")

results_df["p_adjusted"] = p_corrected
results_df["is_significant"] = reject
results_df = results_df.sort_values(by="p_adjusted")

print(results_df)
```

## Check Model Assumptions

```{python}
# Check for high correlation between x variables indicating a violation of the independence assumption

corr_matrix = mega_df.corr()
# Plot heatmap correlations
plt.figure(figsize=(16, 12))
sns.heatmap(corr_matrix, cmap="coolwarm", annot=False, vmin=-1, vmax=1)
plt.title("Correlation Matrix Heatmap")
plt.show()
```


```{python}
# drop highly correlated features
independent_x_vars_df = mega_df.drop(columns = [
    "pm25_max_sd",
    "pm25_mean_sd",
    "pm25_pop_sd",
    "pm25_max_daily_avg",
    "pm25_mean_daily_avg",
    "pm25_pop_daily_avg",
    "civilian_labor_force",
    "employed",
    "unemployed",
    "all_multifamily_permits_per_capita",
    "current_gdp_dollars_thousands_per_capita"
    ])

corr_matrix = independent_x_vars_df.corr()
# Plot heatmap correlations
plt.figure(figsize=(16, 12))
sns.heatmap(corr_matrix, cmap="coolwarm", annot=False, vmin=-1, vmax=1)
plt.title("Correlation Matrix Heatmap")
plt.show()
```

```{python}
# drop columns with high VIF
independent_x_vars_df = independent_x_vars_df.drop(columns = [
    "all_permits_per_capita",
    "quantity_index_gdp",
    "pm25_med_sd",
    "annual_payroll_per_capita",
    "population",
    "tot_employee_count_per_capita",
    "per_capita_personal_income_dollars",
    'est<5_per_capita', 'est5_9_per_capita', 'est10_19_per_capita',
       'est20_49_per_capita', 'est50_99_per_capita', 'est100_249_per_capita',
       'est250_499_per_capita', 'est500_999_per_capita', 'est>1000_per_capita',
       'est1000_1500_per_capita', 'est1500_2500_per_capita',
       'est2500_5000_per_capita', 'est>5000_per_capita'
    ])
```

```{python}
# Check VIF
X = independent_x_vars_df.select_dtypes(include=['number']) 

vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]


print(vif_data[vif_data["VIF"] > 5])
```


## Models

### Set Up Training and Testing Data
```{python}
# set up train and test datasets
y = independent_x_vars_df["has_datacenter"]
X = independent_x_vars_df.drop(columns = ["county_id", "has_datacenter"])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=57, stratify=y)
```

```{python}
# scale features since they have very different ranges
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train.values)
X_test_scaled = scaler.transform(X_test.values)
```

```{python}
smote = SMOTE(sampling_strategy='minority', random_state=57)
X_train_sm, y_train_sm = smote.fit_resample(X_train_scaled, y_train)
```

```{python}
# function to return model accuracy report
def model_accuracy_report(model, X_train, y_train, X_test, y_test):
    # training calculations
    y_pred_train = model.predict(X_train)
    train_acc = sum(y_pred_train == y_train) / len(y_train)
    print(f"Overall Training Accuracy: {train_acc:.4f}")
    
    actual_pos_train = (y_train == 1)
    true_pos_train = (y_pred_train == 1) & actual_pos_train
    tpr_train = sum(true_pos_train) / sum(actual_pos_train)
    print(f"True Positive Training Accuracy: {tpr_train:.4f}")
    
    print("-" * 20) 
    
    # test calculations
    y_pred_test = model.predict(X_test)
    test_acc = sum(y_pred_test == y_test) / len(y_test)
    print(f"Overall Test Accuracy: {test_acc:.4f}")
    
    actual_pos_test = (y_test == 1)
    true_pos_test = (y_pred_test == 1) & actual_pos_test
    tpr_test = sum(true_pos_test) / sum(actual_pos_test)
    print(f"True Positive Test Accuracy: {tpr_test:.4f}")

    ConfusionMatrixDisplay(
    confusion_matrix=confusion_matrix(y_test, y_pred_test), 
    display_labels=model.classes_
    ).plot()

    plt.show()
```

### Logistic Regression

Using class_weight='balanced' since the vast majority of counties do not have a datacenter meaning that if we don't balance the training data it model will tend to just guess that all counties don't have a data center.
```{python}
# train the model
log_reg = LogisticRegression(random_state=57, class_weight='balanced')
log_reg.fit(X_train_sm, y_train_sm)
```

```{python}
# evaluate model performance
print("Logistic Regression")
model_accuracy_report(log_reg, X_train_sm, y_train_sm, X_test_scaled, y_test)

```

#### Interpreting Logistic Model Results

```{python}
coef_df = pd.DataFrame({
    'Variable': X.columns,
    'Coefficient': log_reg.coef_[0]
})

# Add the intercept
intercept_df = pd.DataFrame({'Variable': ['Intercept'], 'Coefficient': log_reg.intercept_})
coef_df = pd.concat([intercept_df, coef_df], ignore_index=True)

print(coef_df)
```


A Durbin-Watson score = 2 indicates perfect independence of the residuals (assumption of Logistic Regression). A score < 2 indicates postive autocorrelation and a score > 2 indicates negative autocorreclation. 
```{python}
# Check for independce of errors
pred_probabilities = log_reg.predict_proba(X)[:, 1]

residuals = y - pred_probabilities

dw_stat = durbin_watson(residuals)
print("Durbin-Watson:", dw_stat)
```



### Random Forest

#### Standard Random Forest Model with SMOTE to balance classes
```{python}
rf_model = RandomForestClassifier()
rf_model.fit(X_train_sm, y_train_sm)
```

```{python}
# evaluate model performance
print("Random Forest with SMOTE")
model_accuracy_report(rf_model, X_train_sm, y_train_sm, X_test_scaled, y_test)

```


#### Balanced Random Forest Model without SMOTE
Using the balanced Random Forest Classifier acheives similar overall accuracy as the standard Random Forest Classifier, but yields a doubleing of true postive rate.
```{python}
brf_model = BalancedRandomForestClassifier(
    n_estimators=100, 
    sampling_strategy="all", 
    replacement=True, 
    random_state=57
)
brf_model.fit(X_train_scaled, y_train)

print("Balanced Random Forest")
model_accuracy_report(brf_model, X_train_scaled, y_train, X_test_scaled, y_test)
```

```{python}
# plot feature importance values for each x variable in the Balanced Random Forest Model
feature_importances = brf_model.feature_importances_
feature_names = X_train.columns 

df_importance = pd.DataFrame({
    'Feature': feature_names,
    'Importance': feature_importances
}).sort_values(by='Importance', ascending=True) 

plt.figure(figsize=(10, 6))
plt.barh(df_importance['Feature'], df_importance['Importance'], color='steelblue')
plt.xlabel('Feature Importance')
plt.title('Feature Importance in Balanced Random Forest Classifier')
plt.tight_layout()
plt.show()
```


#### Balanced Random Forest Model Trained on All Features
This model performs slightly worse on both overall accuracy and the accuracy of predicting counties with datacenters than the previous model which uses fewer features.
```{python}
# set up train and test datasets
y = mega_df["has_datacenter"]
X_full = mega_df.drop(columns = ["county_id", "has_datacenter"])

X_train_full, X_test_full, y_train, y_test = train_test_split(X_full, y, test_size=0.2, random_state=57, stratify=y)

# scale features since they have very different ranges
scaler = StandardScaler()
X_train_scaled_full = scaler.fit_transform(X_train_full.values)
X_test_scaled_full = scaler.transform(X_test_full.values)
```

```{python}
brf_full_model = BalancedRandomForestClassifier(
    n_estimators=100, 
    sampling_strategy="all", 
    replacement=True, 
    random_state=57
)
brf_full_model.fit(X_train_scaled_full, y_train)

print("Balanced Random Forest")
model_accuracy_report(brf_full_model, X_train_scaled_full, y_train, X_test_scaled_full, y_test)
```

```{python}
# plot feature importance values for each x variable in the Balanced Random Forest Model with all x variables
feature_importances = brf_full_model.feature_importances_
feature_names = X_train_full.columns 

df_importance = pd.DataFrame({
    'Feature': feature_names,
    'Importance': feature_importances
}).sort_values(by='Importance', ascending=True) 

plt.figure(figsize=(10, 6))
plt.barh(df_importance['Feature'], df_importance['Importance'], color='steelblue')
plt.xlabel('Feature Importance')
plt.title('Feature Importance in Balanced Random Forest Classifier Full')
plt.tight_layout()
plt.show()
```